# Generated by Django 5.1.5 on 2025-03-23 10:44

import apps.etl.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EtlTrace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Trace',
            },
        ),
        migrations.CreateModel(
            name='ExtractionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Pending'), (2, 'In progress'), (3, 'Success'), (4, 'Failed')], default=1, verbose_name='status')),
                ('source', models.IntegerField(choices=[(1, 'GDACS'), (2, 'PDC'), (3, 'Glide'), (4, 'NOAA-IBTrACS'), (5, 'EM-DAT'), (6, 'IDMC-GIDD'), (7, 'IDMC-IDU'), (8, 'USGS Shakesmaps'), (9, 'Global Flood Database'), (10, 'DFO'), (11, 'STORM'), (12, 'IFRC DREF & EA'), (13, 'WFP-ADAM'), (14, 'DesInventar')], verbose_name='source')),
                ('metadata', models.JSONField(default=dict)),
                ('source_validation_status', models.IntegerField(choices=[(1, 'Success'), (2, 'Failed'), (3, 'No data'), (4, 'No change'), (5, 'No validation')], default=5, verbose_name='source data validation status')),
                ('resp_code', models.IntegerField(blank=True, null=True, verbose_name='HTTP response code')),
                ('resp_data', models.FileField(blank=True, null=True, upload_to=apps.etl.models.extract_data_upload_to, verbose_name='Response data')),
                ('resp_type', models.IntegerField(blank=True, choices=[(1, 'json'), (2, 'csv'), (3, 'text'), (4, 'html'), (5, 'xml'), (6, 'pdf')], null=True, verbose_name='Response type')),
                ('attempt_no', models.IntegerField(blank=True, verbose_name='Attempt number')),
                ('file_hash', models.CharField(blank=True, max_length=500, null=True, verbose_name='File hash value')),
                ('resp_data_type', models.CharField(blank=True, verbose_name='Response data type')),
                ('url', models.URLField(blank=True, verbose_name='url')),
                ('hazard_type', models.CharField(blank=True, choices=[('EQ', 'Earthquake'), ('FL', 'Flood'), ('TC', 'Cyclone'), ('EP', 'Epidemic'), ('FI', 'Food Insecurity'), ('SS', 'Storm Surge'), ('DR', 'Drought'), ('TS', 'Tsunami'), ('CD', 'Cyclonic Wind'), ('WF', 'WildFire'), ('VO', 'Volcano'), ('CW', 'Cold Wave'), ('CE', 'Complex Emergency'), ('EC', 'Extratropical Cyclone'), ('ET', 'Extreme temperature'), ('FA', 'Famine'), ('FR', 'Fire'), ('FF', 'Flash Flood'), ('HT', 'Heat Wave'), ('IN', 'Insect Infestation'), ('LS', 'Land Slide'), ('MS', 'Mud Slide'), ('ST', 'Severe Local Strom'), ('SL', 'Slide'), ('AV', 'Snow Avalanche'), ('AC', 'Tech. Disaster'), ('TO', 'Tornado'), ('VW', 'Violent Wind'), ('WV', 'Wave/Surge'), ('OT', 'Other')], max_length=100, null=True, verbose_name='hazard type')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child_extractions', to='etl.extractiondata')),
                ('revision_id', models.ForeignKey(blank=True, help_text='This id points to the extraction object having same file content', null=True, on_delete=django.db.models.deletion.PROTECT, to='etl.extractiondata', verbose_name='revision id')),
                ('trace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='etl.etltrace')),
            ],
            options={
                'verbose_name': 'Extraction',
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Pending'), (2, 'In progress'), (3, 'Success'), (4, 'Failed')], default=1, verbose_name='status')),
                ('metadata', models.JSONField(default=dict)),
                ('extraction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='etl.extractiondata', verbose_name='extraction')),
                ('trace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='etl.etltrace')),
            ],
            options={
                'verbose_name': 'Transform',
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PyStacLoadData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('item_type', models.IntegerField(choices=[(1, 'Event'), (2, 'Hazard'), (3, 'Impact')], verbose_name='item type')),
                ('collection_id', models.CharField(max_length=250, verbose_name='collection id')),
                ('item', models.JSONField(default=dict, verbose_name='item')),
                ('status', models.IntegerField(choices=[(1, 'Pending'), (3, 'Success'), (4, 'Failed')], default=1, verbose_name='status')),
                ('trace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='etl.etltrace')),
                ('transform_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='etl.transform', verbose_name='transform')),
            ],
            options={
                'verbose_name': 'Stac Item',
                'ordering': ['-id'],
                'abstract': False,
                'indexes': [models.Index(condition=models.Q(('status', 1)), fields=['status'], name='loaddata_pi_status_pending')],
            },
        ),
    ]
