# Generated by Django 5.1.3 on 2024-11-19 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('source', models.IntegerField(choices=[(1, 'Gdacs'), (2, 'pdc')], verbose_name='source')),
                ('url', models.URLField(blank=True, verbose_name='url')),
                ('attempt_no', models.IntegerField(blank=True, verbose_name='attempt number')),
                ('resp_code', models.IntegerField(blank=True, verbose_name='response code')),
                ('status', models.IntegerField(choices=[(1, 'Pending'), (2, 'In progress'), (3, 'Success'), (4, 'Failed')], verbose_name='status')),
                ('resp_data', models.FileField(blank=True, null=True, upload_to='source_raw_data/', verbose_name='resp_data')),
                ('resp_type', models.IntegerField(blank=True, choices=[(1, 'Json'), (2, 'CSV'), (3, 'Text'), (4, 'Html'), (5, 'XML'), (6, 'pdf')], null=True, verbose_name='response type')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child_extraction', to='etl.extractiondata')),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
    ]
