# Generated by Django 5.1.3 on 2024-11-15 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GDACS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('raw_data', models.JSONField(default=dict, verbose_name='raw data')),
                ('log', models.TextField(blank=True, verbose_name='log')),
                ('response_time', models.CharField(blank=True, max_length=100, verbose_name='response time')),
                ('response_code', models.IntegerField(blank=True, verbose_name='response code')),
                ('status', models.IntegerField(choices=[(1, 'In progress'), (2, 'Pending'), (3, 'Success')], verbose_name='status')),
            ],
            options={
                'verbose_name': 'gdac',
                'verbose_name_plural': 'gdacs',
            },
        ),
    ]
