# Generated by Django 5.1.5 on 2025-04-04 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extractiondata',
            name='hazard_type',
        ),
        migrations.RemoveField(
            model_name='extractiondata',
            name='url',
        ),
    ]
