# Generated by Django 5.1.5 on 2025-04-15 10:00

import django.utils.timezone
from django.db import migrations, models

def populate_fields(apps, schema_editor):
    Pystacmodel = apps.get_model('etl','PyStacLoadData')
    Pystacobjects = Pystacmodel.objects.all()
    for component in Pystacobjects:
        data = component.item or {}
        item_id = data.get('id')
        item_datetime = data.get('properties',{}).get('datetime')
        if item_id:
            component.item_id = item_id

        if item_datetime:
            component.item_datetime = item_datetime

        if item_id and item_datetime:
            component.save()

def unpopulate_fields(apps, schema_editor):
    PyStacLoadData = apps.get_model('etl', 'PyStacLoadData')
    for component in PyStacLoadData.objects.all():
        component.item_id = None
        component.item_datetime = None
        component.save()

class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pystacloaddata',
            name='item_datetime',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='item datetime'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pystacloaddata',
            name='item_id',
            field=models.CharField(db_index=True, default='item-default', max_length=150, verbose_name='item Id'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='extractiondata',
            name='source',
            field=models.IntegerField(choices=[(1, 'GDACS'), (2, 'PDC'), (3, 'Glide'), (4, 'NOAA-IBTrACS'), (5, 'EM-DAT'), (6, 'IDMC-GIDD'), (7, 'IDMC-IDU'), (8, 'USGS Shakesmaps'), (9, 'Global Flood Database'), (10, 'DFO'), (11, 'STORM'), (12, 'IFRC DREF & EA'), (13, 'WFP-ADAM'), (14, 'DesInventar')], db_index=True, verbose_name='source'),
        ),
        migrations.AlterField(
            model_name='pystacloaddata',
            name='collection_id',
            field=models.CharField(db_index=True, max_length=250, verbose_name='collection id'),
        ),
        migrations.AlterField(
            model_name='pystacloaddata',
            name='item_type',
            field=models.IntegerField(choices=[(1, 'Event'), (2, 'Hazard'), (3, 'Impact')], db_index=True, verbose_name='item type'),
        ),
        migrations.RunPython(populate_fields, reverse_code=unpopulate_fields),
    ]
