# Generated by Django 5.1.8 on 2025-04-13 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractiondata',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'In progress'), (3, 'Success'), (4, 'Failed'), (5, 'On Retry')], default=1, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='transform',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'In progress'), (3, 'Success'), (4, 'Failed'), (5, 'On Retry')], default=1, verbose_name='status'),
        ),
    ]
