# Generated by Django 5.1.3 on 2024-11-22 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0002_extractiondata_source_validation_fail_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractiondata',
            name='resp_data_type',
            field=models.CharField(blank=True, verbose_name='response data type'),
        ),
    ]
