# Generated by Django 5.2 on 2025-05-15 08:50

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0002_alter_extractiondata_status_alter_transform_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pystacloaddata',
            name='item_datetime',
            field=models.DateTimeField(db_index=True, null=True, verbose_name='item datetime'),
        ),
        migrations.AddField(
            model_name='pystacloaddata',
            name='item_id',
            field=models.CharField(db_index=True, max_length=150, null=True, verbose_name='item Id'),
        ),
        migrations.AddField(
            model_name='pystacloaddata',
            name='item_primary_country',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=150), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='extractiondata',
            name='source',
            field=models.IntegerField(choices=[(1, 'GDACS'), (2, 'PDC'), (3, 'Glide'), (4, 'NOAA-IBTrACS'), (5, 'EM-DAT'), (6, 'IDMC-GIDD'), (7, 'IDMC-IDU'), (8, 'USGS Shakesmaps'), (9, 'Global Flood Database'), (10, 'DFO'), (11, 'STORM'), (12, 'IFRC DREF & EA'), (13, 'WFP-ADAM'), (14, 'DesInventar')], db_index=True, verbose_name='source'),
        ),
        migrations.AlterField(
            model_name='pystacloaddata',
            name='collection_id',
            field=models.CharField(db_index=True, max_length=250, verbose_name='collection id'),
        ),
        migrations.AlterField(
            model_name='pystacloaddata',
            name='item_type',
            field=models.IntegerField(choices=[(1, 'Event'), (2, 'Hazard'), (3, 'Impact')], db_index=True, verbose_name='item type'),
        ),
        migrations.AddIndex(
            model_name='pystacloaddata',
            index=django.contrib.postgres.indexes.GinIndex(fields=['item_primary_country'], name='etl_pystacl_item_pr_bf64af_gin'),
        ),
        migrations.AddIndex(
            model_name='pystacloaddata',
            index=models.Index(fields=['item_id', 'item_type'], name='etl_pystacl_item_id_65649f_idx'),
        ),
    ]
