# Generated by Django 5.2.5 on 2025-11-14 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0003_pystacloaddata_item_datetime_pystacloaddata_item_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transform',
            name='version',
            field=models.CharField(default='1.0.0', max_length=10),
        ),
    ]
