# Generated by Django 5.1.3 on 2024-11-26 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0003_extractiondata_resp_data_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractiondata',
            name='resp_type',
            field=models.IntegerField(blank=True, choices=[(1, 'json'), (2, 'csv'), (3, 'text'), (4, 'html'), (5, 'xml'), (6, 'pdf')], null=True, verbose_name='response type'),
        ),
        migrations.AlterField(
            model_name='extractiondata',
            name='source',
            field=models.IntegerField(choices=[(1, 'GDACS'), (2, 'PDC')], verbose_name='source'),
        ),
        migrations.AlterField(
            model_name='extractiondata',
            name='source_validation_status',
            field=models.IntegerField(choices=[(1, 'Success'), (2, 'Failed'), (3, 'No data'), (4, 'No change')], verbose_name='validation status'),
        ),
    ]
