# Generated by Django 5.2.13 on 2026-06-30 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0004_transform_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pystacloaddata',
            name='item_type',
            field=models.IntegerField(choices=[(1, 'Event'), (2, 'Hazard'), (3, 'Impact'), (4, 'Response')], db_index=True, verbose_name='item type'),
        ),
    ]
