# Generated by Django 5.1.3 on 2024-11-27 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0004_alter_extractiondata_resp_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extractiondata',
            old_name='source_validation_fail_reason',
            new_name='content_validation',
        ),
    ]
