# Generated by Django 5.2.5 on 2026-02-06 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0004_transform_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractiondata',
            name='source',
            field=models.IntegerField(choices=[(1, 'GDACS'), (2, 'PDC'), (3, 'Glide'), (4, 'NOAA-IBTrACS'), (5, 'EM-DAT'), (6, 'IDMC-GIDD'), (7, 'IDMC-IDU'), (8, 'USGS Shakesmaps'), (9, 'Global Flood Database'), (10, 'DFO'), (11, 'STORM'), (12, 'IFRC DREF & EA'), (13, 'WFP-ADAM'), (14, 'DesInventar'), (15, 'Alert Hub')], db_index=True, verbose_name='source'),
        ),
    ]
