# Generated by Django 5.1.3 on 2024-11-28 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0005_rename_source_validation_fail_reason_extractiondata_content_validation'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractiondata',
            name='file_hash',
            field=models.CharField(blank=True, max_length=500, verbose_name='file hash value'),
        ),
        migrations.AddField(
            model_name='extractiondata',
            name='revision_id',
            field=models.ForeignKey(blank=True, help_text='This id points to the extraction object having same file content', null=True, on_delete=django.db.models.deletion.CASCADE, to='etl.extractiondata', verbose_name='revision id'),
        ),
        migrations.AlterField(
            model_name='extractiondata',
            name='resp_data',
            field=models.FileField(blank=True, null=True, upload_to='source_raw_data/', verbose_name='response data'),
        ),
        migrations.AlterField(
            model_name='extractiondata',
            name='source_validation_status',
            field=models.IntegerField(choices=[(1, 'Success'), (2, 'Failed'), (3, 'No data'), (4, 'No change'), (5, 'No validation')], verbose_name='source data validation status'),
        ),
    ]
