# Generated by Django 5.2.13 on 2026-09-29 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0006_alter_extractiondata_source'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='extractiondata',
            index=models.Index(fields=['source', 'file_hash'], name='etl_extract_source_2792f8_idx'),
        ),
    ]
