# Generated by Django 5.1.3 on 2024-12-09 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0006_extractiondata_file_hash_extractiondata_revision_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractiondata',
            name='resp_text',
            field=models.TextField(blank=True, verbose_name='response data in case failure occurs'),
        ),
    ]
