# Generated by Django 5.2.13 on 2026-09-18 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0006_alter_extractiondata_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('resource_type', models.IntegerField(choices=[(1, 'Extraction'), (2, 'Transform'), (3, 'PyStac Load')], verbose_name='resource type')),
                ('source', models.IntegerField(choices=[(1, 'GDACS'), (2, 'PDC'), (3, 'Glide'), (4, 'NOAA-IBTrACS'), (5, 'EM-DAT'), (6, 'IDMC-GIDD'), (7, 'IDMC-IDU'), (8, 'USGS Shakesmaps'), (9, 'Global Flood Database'), (10, 'DFO'), (11, 'STORM'), (12, 'IFRC DREF & EA'), (13, 'WFP-ADAM'), (14, 'DesInventar'), (16, 'CEMS')], verbose_name='source')),
                ('status', models.IntegerField(verbose_name='status')),
                ('count', models.IntegerField(verbose_name='count')),
            ],
            options={
                'verbose_name': 'Status Snapshot',
                'indexes': [models.Index(fields=['resource_type', 'source', 'status', 'created_at'], name='etl_statuss_resourc_7e453e_idx')],
            },
        ),
    ]
