# Generated by Django 5.2.13 on 2026-08-04 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0007_alter_extractiondata_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractiondata',
            name='url',
            field=models.URLField(blank=True, max_length=2048, verbose_name='url'),
        ),
    ]
