# Generated by Django 5.1.3 on 2024-12-12 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0007_extractiondata_resp_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractiondata',
            name='hazard_type',
            field=models.CharField(blank=True, choices=[('EQ', 'Earthquake'), ('FL', 'Flood'), ('TC', 'Cyclone'), ('EP', 'Epidemic'), ('FI', 'Food Insecurity'), ('SS', 'Storm Surge'), ('DR', 'Drought'), ('TS', 'Tsunami'), ('CD', 'Cyclonic Wind'), ('WF', 'WildFire')], max_length=100, verbose_name='hazard type'),
        ),
    ]
