# Generated by Django 5.2.13 on 2026-09-30 11:12

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0007_extractiondata_etl_extract_source_2792f8_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='extractiondata',
            index=django.contrib.postgres.indexes.GinIndex(fields=['metadata'], name='etl_extract_metadat_f9fd19_gin'),
        ),
    ]
