# Generated by Django 5.2.13 on 2026-10-01 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0008_alter_extractiondata_source_url'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='extractiondata',
            index=models.Index(fields=['source', 'status'], name='etl_extract_source_16bcda_idx'),
        ),
        migrations.AddIndex(
            model_name='extractiondata',
            index=models.Index(fields=['source_validation_status'], name='etl_extract_source__ff0648_idx'),
        ),
        migrations.AddIndex(
            model_name='extractiondata',
            index=models.Index(fields=['parent', 'status'], name='etl_extract_parent__46ce28_idx'),
        ),
    ]
