# Generated by Django 5.1.3 on 2024-12-25 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0009_gdacstransformation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gdacstransformation',
            name='item_type',
            field=models.IntegerField(choices=[(1, 'Event'), (2, 'Hazard'), (3, 'Impact')]),
        ),
        migrations.AlterField(
            model_name='gdacstransformation',
            name='status',
            field=models.IntegerField(choices=[(1, 'Failed'), (2, 'Success')]),
        ),
    ]
