# Generated by Django 5.1.3 on 2024-12-31 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0011_alter_extractiondata_hazard_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractiondata',
            name='source',
            field=models.IntegerField(choices=[(1, 'GDACS'), (2, 'PDC'), (3, 'Glide')], verbose_name='source'),
        ),
    ]
