# Generated by Django 5.1.3 on 2025-01-03 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0012_alter_extractiondata_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlideTransformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('data', models.JSONField(default=dict)),
                ('status', models.IntegerField(choices=[(1, 'Failed'), (2, 'Success')])),
                ('failed_reason', models.TextField(blank=True)),
                ('extraction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='etl.extractiondata')),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
    ]
