# Generated by Django 5.1.5 on 2025-01-16 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0013_glidetransformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='gdacstransformation',
            name='load_status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Success'), (3, 'Failed')], default=1),
        ),
        migrations.AlterField(
            model_name='extractiondata',
            name='hazard_type',
            field=models.CharField(blank=True, choices=[('EQ', 'Earthquake'), ('FL', 'Flood'), ('TC', 'Cyclone'), ('EP', 'Epidemic'), ('FI', 'Food Insecurity'), ('SS', 'Storm Surge'), ('DR', 'Drought'), ('TS', 'Tsunami'), ('CD', 'Cyclonic Wind'), ('WF', 'WildFire'), ('VO', 'Volcano'), ('CW', 'Cold Wave'), ('CE', 'Complex Emergency'), ('EC', 'Extratropical Cyclone'), ('ET', 'Extreme temperature'), ('FA', 'Famine'), ('FR', 'Fire'), ('FF', 'Flash Flood'), ('HT', 'Heat Wave'), ('IN', 'Insect Infestation'), ('LS', 'Land Slide'), ('MS', 'Mud Slide'), ('ST', 'Severe Local Strom'), ('SL', 'Slide'), ('AV', 'Snow Avalanche'), ('AC', 'Tech. Disaster'), ('TO', 'Tornado'), ('VW', 'Violent Wind'), ('WV', 'Wave/Surge')], max_length=100, verbose_name='hazard type'),
        ),
        migrations.AlterField(
            model_name='gdacstransformation',
            name='status',
            field=models.IntegerField(choices=[(1, 'Success'), (2, 'Failed')]),
        ),
        migrations.AlterField(
            model_name='glidetransformation',
            name='status',
            field=models.IntegerField(choices=[(1, 'Success'), (2, 'Failed')]),
        ),
    ]
