# Generated by Django 5.1.5 on 2025-01-17 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0014_gdacstransformation_load_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='glidetransformation',
            name='item_type',
            field=models.IntegerField(choices=[(1, 'Event'), (2, 'Hazard')]),
        ),
    ]
