# Generated by Django 5.1.5 on 2025-01-17 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0015_glidetransformation_item_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='glidetransformation',
            name='load_status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Success'), (3, 'Failed')], default=1),
        ),
        migrations.AlterField(
            model_name='glidetransformation',
            name='item_type',
            field=models.IntegerField(choices=[(1, 'Event'), (2, 'Hazard'), (3, 'Impact')]),
        ),
    ]
