# Generated by Django 5.1.5 on 2025-01-17 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0016_glidetransformation_load_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractiondata',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child_extractions', to='etl.extractiondata'),
        ),
    ]
