# Generated by Django 5.1.5 on 2025-01-19 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0017_alter_extractiondata_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='STACItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('item_type', models.IntegerField(choices=[(1, 'Event'), (2, 'Hazard'), (3, 'Impact')], verbose_name='item type')),
                ('collection_id', models.CharField(max_length=250, verbose_name='collection id')),
                ('item', models.JSONField(default=dict, verbose_name='item')),
                ('load_status', models.IntegerField(choices=[(1, 'Pending'), (2, 'Success'), (3, 'Failed')], default=1, verbose_name='load status')),
                ('extraction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='etl.extractiondata', verbose_name='extraction')),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('data', models.JSONField(default=dict, verbose_name='transformed data')),
                ('status', models.IntegerField(choices=[(1, 'Success'), (2, 'Failed')], verbose_name='transform status')),
                ('extraction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='etl.extractiondata', verbose_name='extraction')),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
    ]
