# Generated by Django 5.1.5 on 2025-01-20 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0018_stacitem_transformation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='STACItem',
            new_name='PyStacLoadData',
        ),
        migrations.RemoveField(
            model_name='glidetransformation',
            name='extraction',
        ),
        migrations.RemoveField(
            model_name='transformation',
            name='extraction',
        ),
        migrations.CreateModel(
            name='Transform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(1, 'Success'), (2, 'Failed')], verbose_name='transform status')),
                ('extraction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='etl.extractiondata', verbose_name='extraction')),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='GdacsTransformation',
        ),
        migrations.DeleteModel(
            name='GlideTransformation',
        ),
        migrations.DeleteModel(
            name='Transformation',
        ),
    ]
