# Generated by Django 5.1.5 on 2025-01-20 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0019_rename_stacitem_pystacloaddata_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pystacloaddata',
            name='extraction',
        ),
        migrations.AddField(
            model_name='pystacloaddata',
            name='transform_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='etl.transform', verbose_name='transform'),
        ),
    ]
