# Generated by Django 5.1.5 on 2025-01-20 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0020_remove_pystacloaddata_extraction_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pystacloaddata',
            options={},
        ),
        migrations.AddField(
            model_name='transform',
            name='is_loaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='extractiondata',
            name='source',
            field=models.IntegerField(choices=[(1, 'GDACS'), (2, 'PDC'), (3, 'Glide'), (4, 'IBTrACS')], verbose_name='source'),
        ),
        migrations.AlterField(
            model_name='pystacloaddata',
            name='transform_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='etl.transform', verbose_name='transform'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transform',
            name='extraction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='etl.extractiondata', verbose_name='extraction'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transform',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Success'), (3, 'Failed')], verbose_name='transform status'),
        ),
        migrations.AddIndex(
            model_name='pystacloaddata',
            index=models.Index(condition=models.Q(('load_status', 1)), fields=['load_status'], name='partial_index_on_load_status'),
        ),
    ]
