# Generated by Django 5.1.5 on 2025-01-21 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0021_alter_pystacloaddata_options_transform_is_loaded_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transform',
            name='is_loaded',
            field=models.BooleanField(default=False, help_text='Track whether transformer data has been successfully loaded into the PyStacLoadData table. This flag can be used to re-populate the data in case of any issues with the transformer.'),
        ),
    ]
