# Generated by Django 5.1.5 on 2025-01-21 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0014_alter_extractiondata_hazard_type'),
        ('etl', '0022_alter_transform_is_loaded'),
    ]

    operations = [
    ]
