# Generated by Django 5.1.5 on 2025-01-28 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0023_alter_extractiondata_hazard_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractiondata',
            name='metadata',
            field=models.JSONField(default=dict),
        ),
    ]
