# Generated by Django 5.1.5 on 2025-03-18 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0024_extractiondata_meta_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractiondata',
            name='trace_id',
            field=models.UUIDField(default='ed22c3ae-09ce-47bf-a82d-354b165b3fc6', editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pystacloaddata',
            name='trace_id',
            field=models.UUIDField(default='ed22c3ae-09ce-47bf-a82d-354b165b3fc6', editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transform',
            name='trace_id',
            field=models.UUIDField(default='ed22c3ae-09ce-47bf-a82d-354b165b3fc6', editable=False),
            preserve_default=False,
        ),
    ]
