# Generated by Django 5.1.5 on 2025-03-19 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0025_extractiondata_trace_id_pystacloaddata_trace_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extractiondata',
            name='trace_id',
        ),
        migrations.RemoveField(
            model_name='pystacloaddata',
            name='trace_id',
        ),
        migrations.RemoveField(
            model_name='transform',
            name='trace_id',
        ),
    ]
