# Generated by Django 5.1.5 on 2025-03-19 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0026_remove_extractiondata_trace_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractiondata',
            name='trace_id',
            field=models.UUIDField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='pystacloaddata',
            name='trace_id',
            field=models.UUIDField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='transform',
            name='trace_id',
            field=models.UUIDField(blank=True, db_index=True, editable=False, null=True),
        ),
    ]
