# Generated by Django 5.1.5 on 2025-03-20 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0027_extractiondata_trace_id_pystacloaddata_trace_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractiondata',
            name='trace_id',
            field=models.UUIDField(db_index=True, default='00000000-0000-0000-0000-000000000000', editable=False),
        ),
        migrations.AlterField(
            model_name='pystacloaddata',
            name='trace_id',
            field=models.UUIDField(db_index=True, default='00000000-0000-0000-0000-000000000000', editable=False),
        ),
        migrations.AlterField(
            model_name='transform',
            name='trace_id',
            field=models.UUIDField(db_index=True, default='00000000-0000-0000-0000-000000000000', editable=False),
        ),
    ]
