# Generated by Django 5.1.5 on 2025-03-22 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0028_alter_extractiondata_trace_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtlTrace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='pystacloaddata',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='extractiondata',
            name='trace_id',
        ),
        migrations.RemoveField(
            model_name='pystacloaddata',
            name='trace_id',
        ),
        migrations.RemoveField(
            model_name='transform',
            name='trace_id',
        ),
        migrations.AlterField(
            model_name='extractiondata',
            name='attempt_no',
            field=models.IntegerField(blank=True, verbose_name='Attempt number'),
        ),
        migrations.AlterField(
            model_name='extractiondata',
            name='content_validation',
            field=models.TextField(blank=True, verbose_name='Error message if validation fails'),
        ),
        migrations.AlterField(
            model_name='extractiondata',
            name='file_hash',
            field=models.CharField(blank=True, max_length=500, verbose_name='File hash value'),
        ),
        migrations.AlterField(
            model_name='extractiondata',
            name='resp_code',
            field=models.IntegerField(blank=True, verbose_name='HTTP response code'),
        ),
        migrations.AlterField(
            model_name='extractiondata',
            name='resp_data',
            field=models.FileField(blank=True, null=True, upload_to='source_raw_data/', verbose_name='Response data'),
        ),
        migrations.AlterField(
            model_name='extractiondata',
            name='resp_data_type',
            field=models.CharField(blank=True, verbose_name='Response data type'),
        ),
        migrations.AlterField(
            model_name='extractiondata',
            name='resp_text',
            field=models.TextField(blank=True, verbose_name='Error message if request fails'),
        ),
        migrations.AlterField(
            model_name='extractiondata',
            name='resp_type',
            field=models.IntegerField(blank=True, choices=[(1, 'json'), (2, 'csv'), (3, 'text'), (4, 'html'), (5, 'xml'), (6, 'pdf')], null=True, verbose_name='Response type'),
        ),
        migrations.AlterField(
            model_name='transform',
            name='extraction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='etl.extractiondata', verbose_name='Extraction'),
        ),
        migrations.AddField(
            model_name='extractiondata',
            name='trace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='etl.etltrace'),
        ),
        migrations.AddField(
            model_name='pystacloaddata',
            name='trace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='etl.etltrace'),
        ),
        migrations.AddField(
            model_name='transform',
            name='trace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='etl.etltrace'),
        ),
    ]
