# Generated by Django 5.1.5 on 2025-03-22 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0029_etltrace_alter_pystacloaddata_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='etltrace',
            options={'verbose_name': 'Trace'},
        ),
        migrations.AlterModelOptions(
            name='extractiondata',
            options={'ordering': ['-id'], 'verbose_name': 'Extraction'},
        ),
        migrations.AlterModelOptions(
            name='pystacloaddata',
            options={'ordering': ['-id'], 'verbose_name': 'Stac Item'},
        ),
        migrations.AlterModelOptions(
            name='transform',
            options={'ordering': ['-id'], 'verbose_name': 'Transform'},
        ),
        migrations.AlterField(
            model_name='transform',
            name='extraction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='etl.extractiondata', verbose_name='extraction'),
        ),
    ]
