default_language_version:
  python: python3

# NOTE: Update in .flake8 pyproject.toml as well
exclude: |
    (?x)^(
      \.git|
      __pycache__|
      .*snap_test_.*\.py|
      .+\/.+\/migrations\/.*|
      \.venv
    )

repos:
    hooks:

    hooks:

  # Run the Ruff linter.
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.8
    hooks:
      # Linter
      - id: ruff
        types_or: [python, pyi, jupyter, toml]
        args: [--fix, --exit-non-zero-on-fix]
      # Formatter
      - id: ruff-format
        types_or: [python, pyi, jupyter, toml]

  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.396
    hooks:
      - id: pyright
        verbose: true  # FIXME: Remove me after fixing all issues
        entry: bash -c 'pyright "$@" || true' --  # FIXME: Remove me after fixing all issues
        additional_dependencies:
          [
            beartype,
            einops,
            jax,
            jaxtyping,
            optax,
            pytest,
            typing_extensions,
            wadler_lindig,
          ]
