services:
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  web:
    restart: unless-stopped
    image: etl-montandon/server
    build:
      context: ./
    tty: true
    environment:
      DEBUG: ${DEBUG:-True}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY:?err}
      DB_NAME: ${DB_NAME:-postgres}
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-postgres}
      DB_HOST: ${DB_HOST:-db}
      DB_PORT: ${DB_PORT:-5432}
    command: bash -c "/code/scripts/run_develop.sh"
    volumes:
      - ./:/code
    ports:
      - '8000:8000'
    depends_on:
      - db

volumes:
  postgres-data:

