
x-server: &base_server_setup
  restart: unless-stopped
  image: etl-montandon/server
  build:
    context: ./
  # Used for python debugging.
  stdin_open: true
  tty: true
  env_file:
    - .env
  environment: &base_server_environments
      DJANGO_APP_ENVIRONMENT: ${DJANGO_APP_ENVIRONMENT:-development}
      DJANGO_DEBUG: ${DJANGO_DEBUG:-true}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY:?err}
      DB_NAME: ${DB_NAME:-postgres}
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-postgres}
      DB_HOST: ${DB_HOST:-db}
      DB_PORT: ${DB_PORT:-5432}
      CELERY_BROKER_URL: ${CELERY_BROKER_URL:-amqp://monty:monty@rabbitmq:5672/celery}
      CELERY_RESULT_BACKEND: ${CELERY_RESULT_BACKEND:-redis://redis:6379/0}
      CACHE_REDIS_URL: ${CACHE_REDIS_URL:-redis://redis:6379/2}
      # Health-checks
      HEALTHCHECK_REDIS_URL: ${CELERY_RESULT_BACKEND:-redis://redis:6379/1}
      HEALTHCHECK_RABBITMQ_URL: ${CELERY_BROKER_URL:-amqp://monty:monty@rabbitmq:5672/celery}
      # Geocoder
      # FIXME: Add geocoder to docker compose and use that service here
      GEOCODER_URL: ${GEOCODER_URL?error}
  extra_hosts:
      - "host.docker.internal:host-gateway"
  volumes:
    - .:/code
    - ipython_data_local:/root/.ipython/profile_default   # persist ipython data, including ipython history
    - local_cache_pull:/local-cache-data
  depends_on:
    - db
    - redis
    - rabbitmq

x-worker: &base_worker_setup
  <<: *base_server_setup
  environment:
    <<: *base_server_environments
    DJANGO_APP_TYPE: "worker"

services:
  db:
    image: postgis/postgis:15-3.5-alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:6-alpine
    volumes:
      - redis-data:/data
    # post_start:  # FIXME: Uncomment after github action have docker compose version > 1.30
    #   # NOTE: Set maxmemory for database /0 (celery results backend)
    #   - command: sh -c "redis-cli SELECT 0 && redis-cli CONFIG SET maxmemory 500mb"

  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_VHOST: celery
      RABBITMQ_DEFAULT_USER: monty
      RABBITMQ_DEFAULT_PASS: monty
    ports:
      - 127.0.0.1:15672:15672  # Managements console
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  web:
    <<: *base_server_setup
    environment:
      <<: *base_server_environments
      DJANGO_APP_TYPE: "web"
    command: bash -c "/code/scripts/dev/run_web.sh"
    ports:
      - 8000:8000

  worker-beat:
    <<: *base_worker_setup
    command: bash -c "./scripts/dev/run_worker_beat.sh"

  worker:
    <<: *base_worker_setup
    command: bash -c "./scripts/dev/run_worker.sh"

  # NOTE: Use `docker compose exec worker celery -A main events` for basic cli dashboard
  worker-monitor:
    <<: *base_worker_setup
    command: bash -c "celery -A main flower --port=8000"
    profiles:
      - extra
    ports:
      - 127.0.0.1:8001:8000


volumes:
  postgres-data:
  redis-data:
  rabbitmq_data:
  ipython_data_local:
  local_cache_pull:
