services:
  web:
    image: $DOCKER_IMAGE_BACKEND
    build: !reset null
    env_file: !reset null
    environment:
      CI: "true"
    volumes:
      - ./coverage/:/code/coverage/
  geocoding-service:
    image: ghcr.io/ifrcgo/geocoding-service:main.9ddfeda
    command: /bin/sh -c "uvicorn service:app --host 0.0.0.0 --port 8001 --reload --workers 1"
  celery-beat: !reset null
  worker:  !reset null
