services:
  web:
    image: $DOCKER_IMAGE_BACKEND
    build: !reset null
    env_file: !reset null
    environment:
      CI: "true"
    volumes:
      - ./coverage/:/code/coverage/
  geocoding-service:
    image: ghcr.io/ifrcgo/geocoding-service:main.99b10c8
  celery-beat: !reset null
  worker:  !reset null
