type AppEnumCollection {
  ExtractionDataSource: [AppEnumCollectionExtractionDataSource!]!
  ExtractionDataStatus: [AppEnumCollectionExtractionDataStatus!]!
  ExtractionDataSourceValidationStatus: [AppEnumCollectionExtractionDataSourceValidationStatus!]!
  PyStacLoadDataStatus: [AppEnumCollectionPyStacLoadDataStatus!]!
  PyStacLoadDataItemType: [AppEnumCollectionPyStacLoadDataItemType!]!
}

type AppEnumCollectionExtractionDataSource {
  key: ExtractionSourceTypeEnum!
  label: String!
}

type AppEnumCollectionExtractionDataSourceValidationStatus {
  key: ExtractionDataValidationStatusTypeEnum!
  label: String!
}

type AppEnumCollectionExtractionDataStatus {
  key: ExtractionDataStatusTypeEnum!
  label: String!
}

type AppEnumCollectionPyStacLoadDataItemType {
  key: PyStacLoadDataItemTypeEnum!
  label: String!
}

type AppEnumCollectionPyStacLoadDataStatus {
  key: PyStacLoadDataStatusEnum!
  label: String!
}

"""Date with time (isoformat)"""
scalar DateTime

input DatetimeDatetimeFilterLookup {
  """Exact match. Filter will be skipped on `null` value"""
  exact: DateTime

  """Assignment test. Filter will be skipped on `null` value"""
  isNull: Boolean

  """
  Exact match of items in a given list. Filter will be skipped on `null` value
  """
  inList: [DateTime!]

  """Greater than. Filter will be skipped on `null` value"""
  gt: DateTime

  """Greater than or equal to. Filter will be skipped on `null` value"""
  gte: DateTime

  """Less than. Filter will be skipped on `null` value"""
  lt: DateTime

  """Less than or equal to. Filter will be skipped on `null` value"""
  lte: DateTime

  """Inclusive range test (between)"""
  range: DatetimeRangeLookup
  year: IntComparisonFilterLookup
  month: IntComparisonFilterLookup
  day: IntComparisonFilterLookup
  weekDay: IntComparisonFilterLookup
  isoWeekDay: IntComparisonFilterLookup
  week: IntComparisonFilterLookup
  isoYear: IntComparisonFilterLookup
  quarter: IntComparisonFilterLookup
  hour: IntComparisonFilterLookup
  minute: IntComparisonFilterLookup
  second: IntComparisonFilterLookup
  date: IntComparisonFilterLookup
  time: IntComparisonFilterLookup
}

input DatetimeRangeLookup {
  start: DateTime = null
  end: DateTime = null
}

input ExtractionDataFilter {
  createdAt: DatetimeDatetimeFilterLookup
  source: ExtractionSourceTypeEnum!
  status: ExtractionDataStatusTypeEnum!
  AND: ExtractionDataFilter
  OR: ExtractionDataFilter
  NOT: ExtractionDataFilter
  DISTINCT: Boolean
}

enum ExtractionDataStatusTypeEnum {
  PENDING
  IN_PROGRESS
  SUCCESS
  FAILED
  ON_RETRY
}

enum ExtractionDataValidationStatusTypeEnum {
  SUCCESS
  FAILED
  NO_DATA
  NO_CHANGE
  NO_VALIDATION
}

enum ExtractionSourceTypeEnum {
  GDACS
  PDC
  GLIDE
  IBTRACS
  EMDAT
  GIDD
  IDU
  USGS
  GFD
  DFO
  STORM
  DREF
  WFPADAM
  DESINVENTAR
}

input IntComparisonFilterLookup {
  """Exact match. Filter will be skipped on `null` value"""
  exact: Int

  """Assignment test. Filter will be skipped on `null` value"""
  isNull: Boolean

  """
  Exact match of items in a given list. Filter will be skipped on `null` value
  """
  inList: [Int!]

  """Greater than. Filter will be skipped on `null` value"""
  gt: Int

  """Greater than or equal to. Filter will be skipped on `null` value"""
  gte: Int

  """Less than. Filter will be skipped on `null` value"""
  lt: Int

  """Less than or equal to. Filter will be skipped on `null` value"""
  lte: Int

  """Inclusive range test (between)"""
  range: IntRangeLookup
}

input IntRangeLookup {
  start: Int = null
  end: Int = null
}

type Mutation {
  public: PublicMutation!
  private: PrivateMutation!
}

input OffsetPaginationInput {
  offset: Int! = 0
  limit: Int
}

type PrivateMutation {
  id: ID!
}

type PrivateQuery {
  extractionList(filters: ExtractionDataFilter, pagination: OffsetPaginationInput): RawExtractiondatatypeCountList!
  totalCount: [StatusCount!]!
  statusSourceCounts: [StatusSourceCount!]!
  validationStatusSourceCounts: [ValStatusSourceCount!]!
  id: ID!
}

type PublicMutation {
  id: ID!
}

type PublicQuery {
  noop: ID!
  id: ID!
}

enum PyStacLoadDataItemTypeEnum {
  EVENT
  HAZARD
  IMPACT
}

enum PyStacLoadDataStatusEnum {
  PENDING
  SUCCESS
  FAILED
}

type Query {
  public: PublicQuery!
  private: PrivateQuery!
  enums: AppEnumCollection!
}

type RawExtractiondatatype {
  id: ID!
  source: ExtractionSourceTypeEnum!
  status: ExtractionDataStatusTypeEnum!
  url: String!
  respCode: Int
  respDataType: String!
  parentId: Int
  sourceValidationStatus: Int!
  hazardType: String
  traceId: Int!
}

type RawExtractiondatatypeCountList {
  limit: Int!
  offset: Int!
  count: Int!
  items: [RawExtractiondatatype!]!
}

type StatusCount {
  inProgressCount: Int!
  successCount: Int!
  failedCount: Int!
  pendingCount: Int!
}

type StatusSourceCount {
  source: ExtractionSourceTypeEnum!
  inProgressCount: Int!
  successCount: Int!
  failedCount: Int!
  pendingCount: Int!
}

type ValStatusSourceCount {
  source: ExtractionSourceTypeEnum!
  successCount: Int!
  failedCount: Int!
  noDataCount: Int!
  noChangeCount: Int!
  noValidationCount: Int!
}
