"""
Django settings for etl_montandon project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
import socket
import typing
from datetime import date
from pathlib import Path

import environ
from azure.identity import DefaultAzureCredential

from main import sentry

from .logging import log_render_custom_field

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# TODO: create source_config.py and read env

env = environ.Env(
    APP_LOG_LEVEL=(str, "INFO"),
    DJANGO_SECRET_KEY=str,
    DJANGO_DEBUG=(bool, False),
    DJANGO_CORS_ORIGIN_REGEX_WHITELIST=(list, []),
    DJANGO_ALLOWED_HOSTS=(list, ["*"]),
    DJANGO_APP_ENVIRONMENT=(str, "development"),
    DJANGO_APP_TYPE=str,  # web/worker
    DJANGO_TIME_ZONE=(str, "UTC"),
    ENABLE_DEBUG_TOOLBAR=(bool, False),
    # Database
    DB_NAME=str,
    DB_USER=str,
    DB_PASSWORD=str,
    DB_HOST=str,
    DB_PORT=int,
    # Celery
    CELERY_RABBITMQ_CONNECTION_STRING=str,
    CELERY_RABBITMQ_VHOST=str,
    CELERY_RESULT_BACKEND=str,
    # Cache
    CACHE_REDIS_URL=str,
    TEST_CACHE_REDIS_URL=(str, None),
    # Storage
    # -- Static, Media configs
    DJANGO_STATIC_URL=(str, "/static/"),
    DJANGO_MEDIA_URL=(str, "/media/"),
    # -- File System
    DJANGO_STATIC_ROOT=(str, os.path.join(BASE_DIR, "assets/static")),  # Where to store
    DJANGO_MEDIA_ROOT=(str, os.path.join(BASE_DIR, "assets/media")),  # Where to store
    # -- Azure blob storage (NOTE: High priority then S3)
    AZURE_STORAGE_ENABLE=(bool, False),
    AZURE_STORAGE_MEDIA_CONTAINER=str,  # media
    AZURE_STORAGE_STATIC_CONTAINER=str,  # static
    AZURE_STORAGE_CONNECTION_STRING=(str, None),
    AZURE_STORAGE_ACCOUNT_NAME=str,
    AZURE_STORAGE_ACCOUNT_KEY=(str, None),
    AZURE_STORAGE_TOKEN_CREDENTIAL=(str, None),
    AZURE_STORAGE_MANAGED_IDENTITY=(bool, False),
    # -- S3
    AWS_S3_BUCKET_ENABLE=(bool, False),
    AWS_S3_ENDPOINT_URL=str,
    AWS_S3_ACCESS_KEY_ID=str,
    AWS_S3_SECRET_ACCESS_KEY=str,
    AWS_S3_REGION=str,
    AWS_S3_MEDIA_BUCKET_NAME=str,
    AWS_S3_STATIC_BUCKET_NAME=str,
    # Sentry
    SENTRY_DSN=(str, None),
    SENTRY_DEBUG=(bool, False),
    SENTRY_TRACES_SAMPLE_RATE=(float, 0.2),
    SENTRY_PROFILE_SAMPLE_RATE=(float, 0.2),
    SENTRY_MONITOR_CELERY_BEAT_TASKS=(bool, True),
    # External services
    GEOCODER_URL=str,
    # NOTE:
    # /stac is not required for internal service. eg: http://montandon-eoapi-stac.montandon-eoapi.svc.cluster.local:8080
    # /stac is required for external domain. eg:  https://montandon-eoapi-stage.monty.org/stac
    EOAPI_STAC_API_INTERNAL=(str, None),
    EOAPI_SYNC_LIMIT=(int, 10000),
    EOAPI_STAC_API_PUBLIC=(str, None),
    REQUESTS_PROXY_TO_USE=(str, None),  # NOTE: For more detail look at ./README.md
    # Sources
    # FIXME: Check if all start dates are used
    DESINVENTAR_DATA_URL=(str, "https://www.desinventar.net"),
    EMDAT_AUTHORIZATION_KEY=(str, None),
    EMDAT_START_YEAR=(str, 1900),
    EMDAT_END_YEAR=(str, 2024),
    EMDAT_URL=(str, "https://api.emdat.be"),
    GDACS_START_DATE=(str, date.today().replace(day=1).isoformat()),
    GDACS_URL=(str, "https://www.gdacs.org"),
    GFD_CREDENTIAL=(str, None),
    GFD_SERVICE_ACCOUNT=(str, None),
    GLIDE_START_DATE=(str, date.today().replace(day=1).isoformat()),
    GLIDE_URL=(str, "https://www.glidenumber.net"),
    IBTRACS_DATA_URL=(str, "https://www.ncei.noaa.gov"),
    IDMC_CLIENT_ID=(str, None),
    IDMC_DATA_URL=(str, "https://helix-tools-api.idmcdb.org"),
    IFRC_DATA_URL=(str, "https://goadmin.ifrc.org"),
    IFRC_EVENT_START_DATE=(str, date.today().replace(day=1).isoformat()),
    PDC_ARCGIS_DOMAIN=(str, "https://partners.pdc.org"),
    PDC_ARCGIS_PASSWORD=(str, None),
    PDC_ARCGIS_USERNAME=(str, None),
    PDC_SENTRY_AUTHORIZATION_KEY=(str, None),
    PDC_SENTRY_BASE_URL=(str, "https://sentry.pdc.org"),
    PDC_START_DATE=(str, date.today().replace(day=1).isoformat()),
    PDC_EXTRACTION_INTERVAL_YEARS=(int, 2),
    USGS_DATA_URL=(str, "https://earthquake.usgs.gov"),
    USGS_START_DATE=(str, date.today().replace(day=1).isoformat()),
    TRANSFORM_SUCCESS_RATE=(int, 80),
    #  transformer version
    GDACS_TRANSFORMER_VERSION=(str, "1.0.0"),
    GLIDE_TRANSFORMER_VERSION=(str, "1.0.0"),
    EMDAT_TRANSFORMER_VERSION=(str, "1.0.0"),
    IFRC_TRANSFORMER_VERSION=(str, "1.0.0"),
    DESINVENTAR_TRANSFROMER_VERSION=(str, "1.0.0"),
    GFD_TRANSFORMER_VERSION=(str, "1.0.0"),
    USGS_TRANSFORMER_VERSION=(str, "1.0.0"),
    PDC_TRANSFORMER_VERSION=(str, "1.0.0"),
    IDU_TRANSFORMER_VERSION=(str, "1.0.0"),
    GIDD_TRANSFORMER_VERSION=(str, "1.0.0"),
    IBTRACS_TRANSFORMER_VERSION=(str, "1.0.0"),
)


EOAPI_STAC_API_INTERNAL = env("EOAPI_STAC_API_INTERNAL")
EOAPI_SYNC_LIMIT = env("EOAPI_SYNC_LIMIT")
# NOTE We add EOAPI_STAC_API_PUBLIC field to be ingested within stac items
# so that the links can be accessed outside of cluster
EOAPI_STAC_API_PUBLIC = env("EOAPI_STAC_API_PUBLIC")
GEOCODER_URL = env("GEOCODER_URL")
REQUESTS_PROXY_TO_USE = env("REQUESTS_PROXY_TO_USE")

DESINVENTAR_DATA_URL = env("DESINVENTAR_DATA_URL")
EMDAT_AUTHORIZATION_KEY = env("EMDAT_AUTHORIZATION_KEY")
EMDAT_START_YEAR = env("EMDAT_START_YEAR")
EMDAT_END_YEAR = env("EMDAT_END_YEAR")
EMDAT_URL = env("EMDAT_URL")
GDACS_START_DATE = env("GDACS_START_DATE")
GDACS_URL = env("GDACS_URL")
GFD_CREDENTIAL = env("GFD_CREDENTIAL")
GFD_SERVICE_ACCOUNT = env("GFD_SERVICE_ACCOUNT")
GLIDE_START_DATE = env("GLIDE_START_DATE")
GLIDE_URL = env("GLIDE_URL")
IDMC_CLIENT_ID = env("IDMC_CLIENT_ID")
IDMC_DATA_URL = env("IDMC_DATA_URL")
IFRC_DATA_URL = env("IFRC_DATA_URL")
IFRC_EVENT_START_DATE = env("IFRC_EVENT_START_DATE")
PDC_ARCGIS_DOMAIN = env("PDC_ARCGIS_DOMAIN")
PDC_ARCGIS_PASSWORD = env("PDC_ARCGIS_PASSWORD")
PDC_ARCGIS_USERNAME = env("PDC_ARCGIS_USERNAME")
PDC_SENTRY_AUTHORIZATION_KEY = env("PDC_SENTRY_AUTHORIZATION_KEY")
PDC_SENTRY_BASE_URL = env("PDC_SENTRY_BASE_URL")
PDC_START_DATE = env("PDC_START_DATE")
USGS_DATA_URL = env("USGS_DATA_URL")
USGS_START_DATE = env("USGS_START_DATE")


IBTRACS_DATA_URL = env("IBTRACS_DATA_URL")
TRANSFORM_SUCCESS_RATE = env("TRANSFORM_SUCCESS_RATE")

TIME_ZONE = env("DJANGO_TIME_ZONE")
SECRET_KEY = env("DJANGO_SECRET_KEY")
DJANGO_APP_ENVIRONMENT = env("DJANGO_APP_ENVIRONMENT")
DJANGO_APP_TYPE = env("DJANGO_APP_TYPE")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DJANGO_DEBUG")

ALLOWED_HOSTS = typing.cast(list[str], env("DJANGO_ALLOWED_HOSTS"))

# Celery
CELERY_BROKER_URL = f"{env('CELERY_RABBITMQ_CONNECTION_STRING')}{env('CELERY_RABBITMQ_VHOST')}"
CELERY_RESULT_BACKEND = env("CELERY_RESULT_BACKEND")
CELERY_TIMEZONE = TIME_ZONE
CELERY_EVENT_QUEUE_PREFIX = "etl-celery-"
CELERY_ACKS_LATE = True
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
# Hard time limit for tasks (kill if exceeded)
CELERY_TASK_TIME_LIMIT = 7200 * 10  # seconds (2 hours)
# Soft time limit (graceful stop before hard limit)
CELERY_TASK_SOFT_TIME_LIMIT = 7000 * 5

# Per-consumer prefetch (fixes queue stall)
CELERY_BROKER_TRANSPORT_OPTIONS = {"qos_global": False}
# Task reliability
CELERY_TASK_ACKS_LATE = True
CELERY_TASK_REJECT_ON_WORKER_LOST = True
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
# Heartbeat & timeout
CELERY_BROKER_HEARTBEAT = 60 * 5  # or more for long tasks
CELERY_BROKER_CONNECTION_TIMEOUT = 30 * 3  # seconds

CELERY_BEAT_SCHEDULER = "django_celery_beat.schedulers:DatabaseScheduler"

# Redis lock
DEFAULT_REDIS_LOCK_EXPIRE = 30 * 60  # Lock expires in 30 mins

CACHE_REDIS_URL = env("CACHE_REDIS_URL")
TEST_CACHE_REDIS_URL = env("TEST_CACHE_REDIS_URL")

# transformer version
GDACS_TRANSFORMER_VERSION = env("GDACS_TRANSFORMER_VERSION")
GLIDE_TRANSFORMER_VERSION = env("GLIDE_TRANSFORMER_VERSION")
EMDAT_TRANSFORMER_VERSION = env("EMDAT_TRANSFORMER_VERSION")
IFRC_TRANSFORMER_VERSION = env("IFRC_TRANSFORMER_VERSION")
DESINVENTAR_TRANSFROMER_VERSION = env("DESINVENTAR_TRANSFROMER_VERSION")
GFD_TRANSFORMER_VERSION = env("GFD_TRANSFORMER_VERSION")
USGS_TRANSFORMER_VERSION = env("USGS_TRANSFORMER_VERSION")
PDC_TRANSFORMER_VERSION = env("PDC_TRANSFORMER_VERSION")
IDU_TRANSFORMER_VERSION = env("IDU_TRANSFORMER_VERSION")
GIDD_TRANSFORMER_VERSION = env("GIDD_TRANSFORMER_VERSION")
IBTRACS_TRANSFORMER_VERSION = env("IBTRACS_TRANSFORMER_VERSION")


CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": CACHE_REDIS_URL,
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
        "KEY_PREFIX": "djc-",
    },
    "local-memory": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
    },
}

# Application definition

INSTALLED_APPS = [
    # Core
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # External
    "django_celery_beat",
    "djangoql",
    "corsheaders",
    "health_check",
    # Internal
    "apps.common",
    "apps.etl",
    "apps.user",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "main.urls"

# Strawberry
# -- Pagination
STRAWBERRY_ENUM_TO_STRAWBERRY_ENUM_MAP = "main.graphql.enums.ENUM_TO_STRAWBERRY_ENUM_MAP"
STRAWBERRY_DEFAULT_PAGINATION_LIMIT = 50
STRAWBERRY_MAX_PAGINATION_LIMIT = 100

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "main.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.contrib.gis.db.backends.postgis",
        "HOST": env("DB_HOST"),
        "PORT": env("DB_PORT"),
        "NAME": env("DB_NAME"),
        "USER": env("DB_USER"),
        "PASSWORD": env("DB_PASSWORD"),
    },
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]
AUTH_USER_MODEL = "user.User"

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/
# TODO: Use custom config for static files
STATICFILES_DIRS = [
    str(BASE_DIR.joinpath("apps/static")),
]

STATIC_URL = env("DJANGO_STATIC_URL")
MEDIA_URL = env("DJANGO_MEDIA_URL")

if env("AZURE_STORAGE_ENABLE"):
    AZURE_STORAGE_CONFIG_OPTIONS = {
        "connection_string": env("AZURE_STORAGE_CONNECTION_STRING"),
        "overwrite_files": False,
    }

    if not env("AZURE_STORAGE_CONNECTION_STRING"):
        AZURE_STORAGE_CONFIG_OPTIONS.update(
            {
                "account_name": env("AZURE_STORAGE_ACCOUNT_NAME"),
                "account_key": env("AZURE_STORAGE_ACCOUNT_KEY"),
                "token_credential": env("AZURE_STORAGE_TOKEN_CREDENTIAL"),
            }
        )

        if env("AZURE_STORAGE_MANAGED_IDENTITY"):
            AZURE_STORAGE_CONFIG_OPTIONS["token_credential"] = DefaultAzureCredential()

    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.azure_storage.AzureStorage",
            "OPTIONS": {
                **AZURE_STORAGE_CONFIG_OPTIONS,
                "azure_container": env("AZURE_STORAGE_MEDIA_CONTAINER"),
            },
        },
        "staticfiles": {
            "BACKEND": "storages.backends.azure_storage.AzureStorage",
            "OPTIONS": {
                **AZURE_STORAGE_CONFIG_OPTIONS,
                "azure_container": env("AZURE_STORAGE_STATIC_CONTAINER"),
                "overwrite_files": True,
            },
        },
    }

elif env("AWS_S3_BUCKET_ENABLE"):
    AWS_S3_ENDPOINT_URL = env("AWS_S3_ENDPOINT_URL")

    AWS_S3_ACCESS_KEY_ID = env("AWS_S3_ACCESS_KEY_ID")
    AWS_S3_SECRET_ACCESS_KEY = env("AWS_S3_SECRET_ACCESS_KEY")
    AWS_S3_REGION_NAME = env("AWS_S3_REGION")

    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3.S3Storage",
            "OPTIONS": {
                "bucket_name": env("AWS_S3_MEDIA_BUCKET_NAME"),
                "location": "media/",
                "file_overwrite": False,
            },
        },
        "staticfiles": {
            "BACKEND": "storages.backends.s3.S3Storage",
            "OPTIONS": {
                "bucket_name": env("AWS_S3_STATIC_BUCKET_NAME"),
                "querystring_auth": False,
                "location": "static/",
                "file_overwrite": True,
            },
        },
    }

else:
    STATIC_ROOT = env("DJANGO_STATIC_ROOT")
    MEDIA_ROOT = env("DJANGO_MEDIA_ROOT")

# CORS
if not env("DJANGO_CORS_ORIGIN_REGEX_WHITELIST"):
    CORS_ORIGIN_ALLOW_ALL = True
else:
    # Example ^https://[\w-]+\.mapswipe\.org$
    CORS_ORIGIN_REGEX_WHITELIST = env("DJANGO_CORS_ORIGIN_REGEX_WHITELIST")


CORS_ALLOW_CREDENTIALS = True
CORS_URLS_REGEX = r"(^/media/.*$)|(^/graphql/$)"
CORS_ALLOW_METHODS = (
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
)

CORS_ALLOW_HEADERS = (
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
    # Required by sentry
    "sentry-trace",
    "baggage",
)

# Sentry Config
SENTRY_DSN = env("SENTRY_DSN")
SENTRY_ENABLED = False
SENTRY_MONITOR_CELERY_BEAT_TASKS = env("SENTRY_MONITOR_CELERY_BEAT_TASKS")
if SENTRY_DSN is not None:
    SENTRY_ENABLED = True
    SENTRY_CONFIG = {
        "dsn": SENTRY_DSN,
        "send_default_pii": True,
        # TODO: define release
        # "release": env("APP_RELEASE"),
        "environment": DJANGO_APP_ENVIRONMENT,
        "traces_sample_rate": env("SENTRY_TRACES_SAMPLE_RATE"),
        "profiles_sample_rate": env("SENTRY_PROFILE_SAMPLE_RATE"),
        "debug": env("SENTRY_DEBUG"),
    }
    SENTRY_ADDITIONAL_CONFIG = {
        "tags": {
            "site": ",".join(set(ALLOWED_HOSTS)),
        },
        "app_type": DJANGO_APP_TYPE,
    }
    sentry.init_sentry()


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Logging

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "filters": {
        "render_extra_context": {
            "()": "django.utils.log.CallbackFilter",
            "callback": log_render_custom_field,
        }
    },
    "formatters": {
        "simple": {
            "format": ("%(asctime)s: - %(short_name)s - %(message)s %(context)s"),
            "datefmt": "%Y-%m-%dT%H:%M:%S",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "simple",
            "filters": ["render_extra_context"],
        },
    },
    "loggers": {
        **{
            app: {
                "level": env("APP_LOG_LEVEL"),
                "handlers": ["console"],
                "propagate": False,
            }
            for app in ["apps", "main", "utils", "celery", "django"]
        },
        # NOTE: Azure provides high amount of logs for INFO
        "azure.core.pipeline.policies.http_logging_policy": {
            "level": "WARNING",
            "handlers": ["console"],
            "propagate": False,
        },
    },
    "root": {
        "level": env("APP_LOG_LEVEL"),
        "handlers": ["console"],
    },
}

if DEBUG:
    LOGGING = {
        **LOGGING,
        "formatters": {
            **LOGGING["formatters"],
            "colored_verbose": {
                "()": "colorlog.ColoredFormatter",
                "format": ("%(log_color)s%(asctime)s: %(red)s %(short_name)-s%(reset)s %(blue)s%(message)s %(context)s"),
                "datefmt": "%m/%d %H:%M:%S",
            },
        },
        "handlers": {
            **LOGGING["handlers"],
            "colored_console": {
                "class": "logging.StreamHandler",
                "formatter": "colored_verbose",
                "filters": ["render_extra_context"],
            },
        },
        "loggers": {
            **{
                key: {
                    **logger,
                    "handlers": ["colored_console"],
                }
                for key, logger in LOGGING["loggers"].items()
            },
        },
        "root": {
            "level": env("APP_LOG_LEVEL"),
            "handlers": ["colored_console"],
        },
    }

ENABLE_DEBUG_TOOLBAR = env("ENABLE_DEBUG_TOOLBAR")
if DEBUG and ENABLE_DEBUG_TOOLBAR:
    INSTALLED_APPS.append("debug_toolbar")
    MIDDLEWARE.append("debug_toolbar.middleware.DebugToolbarMiddleware")
    INTERNAL_IPS = [
        "127.0.0.1",
        ".".join(socket.gethostbyname(socket.gethostname()).rsplit(".")[:-1]) + ".1",
    ]

# Manual checks
import main.checks  # noqa: F401 E402
