kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ template "montandon-etl.fullname" . }}-api-configmap
  labels:
    app: {{ include "montandon-etl.fullname" . }}
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
data:
  DJANGO_DEBUG: {{ required "env.DJANGO_DEBUG" .Values.env.DJANGO_DEBUG | quote }}
  DJANGO_APP_ENVIRONMENT: {{ .Values.environment | quote | upper }}
  DJANGO_TIME_ZONE: {{ default "UTC" .Values.env.DJANGO_TIME_ZONE | quote }}
  DJANGO_ALLOWED_HOSTS: {{ required "env.DJANGO_ALLOWED_HOSTS" .Values.env.DJANGO_ALLOWED_HOSTS | quote }}

  # ETL Load config
  EOAPI_DOMAIN: {{ required "env.EOAPI_DOMAIN" .Values.env.EOAPI_DOMAIN | quote }}
  DESINVENTAR_DATA_URL: {{ required "env.DESINVENTAR_DATA_URL" .Values.env.DESINVENTAR_DATA_URL | quote }}
  PDC_BASE_URL: {{ required "env.PDC_BASE_URL" .Values.env.PDC_BASE_URL | quote }}
  GLIDE_URL: {{ required "env.GLIDE_URL" .Values.env.GLIDE_URL | quote }}
  GDACS_URL: {{ required "env.GDACS_URL" .Values.env.GDACS_URL | quote }}
  EMDAT_URL: {{ required "env.EMDAT_URL" .Values.env.EMDAT_URL | quote }}
  ARC_DOMAIN: {{ required "env.ARC_DOMAIN" .Values.env.ARC_DOMAIN | quote }}
  IFRC_DATA_URL: {{ required "env.IFRC_DATA_URL" .Values.env.IFRC_DATA_URL | quote }}

  {{- if .Values.env.AZURE_STORAGE_ENABLE }}
  # Azure configs
  AZURE_STORAGE_ENABLE: "true"
  # TODO: Add support for AZURE_STORAGE_TOKEN_CREDENTIAL
  AZURE_STORAGE_MANAGED_IDENTITY: "true"
  AZURE_STORAGE_ACCOUNT_NAME: {{ required "env.AZURE_STORAGE_ACCOUNT_NAME" .Values.env.AZURE_STORAGE_ACCOUNT_NAME | quote }}
  AZURE_STORAGE_MEDIA_CONTAINER: {{ required "env.AZURE_STORAGE_MEDIA_CONTAINER" .Values.env.AZURE_STORAGE_MEDIA_CONTAINER | quote }}
  AZURE_STORAGE_STATIC_CONTAINER: {{ required "env.AZURE_STORAGE_STATIC_CONTAINER" .Values.env.AZURE_STORAGE_STATIC_CONTAINER | quote }}
  {{- end }}

  {{- if .Values.minio.enabled }}
  AWS_S3_BUCKET_ENABLE: "true"
  AWS_S3_MEDIA_BUCKET_NAME: "montandon-etl-data"
  AWS_S3_STATIC_BUCKET_NAME: "montandon-etl-static"
  {{- end }}

  # Additional configs
  {{- range $name, $value := .Values.envAdditional }}
  {{ $name }}: {{ $value | quote }}
  {{- end }}
