{{- if not .Values.azure.aksSecretsProviderAvailable -}}

kind: Secret
apiVersion: v1
metadata:
  name: {{ template "montandon-etl.secretname" . }}
  labels:
    app: {{ include "montandon-etl.fullname" . }}
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
type: Opaque
stringData:
  DJANGO_SECRET_KEY: {{ required "secrets.DJANGO_SECRET_KEY" .Values.secrets.DJANGO_SECRET_KEY | quote }}

  # Sentry
  SENTRY_DSN: {{ .Values.secrets.SENTRY_DSN | quote }}

  # Database
  {{- if .Values.postgresql.enabled }}
  DB_NAME: {{ .Values.postgresql.auth.database | quote }}
  DB_USER: "postgres"
  DB_PASSWORD: {{ .Values.postgresql.auth.postgresPassword | quote }}
  DB_HOST: {{ include "postgresql.v1.primary.fullname" .Subcharts.postgresql }}
  DB_PORT: {{ include "postgresql.v1.service.port" .Subcharts.postgresql | quote }}
  {{- else }}
  DB_NAME: {{ required "secrets.DB_NAME" .Values.secrets.DB_NAME | quote }}
  DB_USER: {{ required "secrets.DB_USER" .Values.secrets.DB_USER | quote }}
  DB_PASSWORD: {{ required "secrets.DB_PASSWORD" .Values.secrets.DB_PASSWORD | quote }}
  DB_HOST: {{ required "secrets.DB_HOST" .Values.secrets.DB_HOST | quote }}
  DB_PORT: {{ required "secrets.DB_PORT" .Values.secrets.DB_PORT | quote }}
  {{- end }}

  # Rabbitmq
  {{- if .Values.rabbitmq.enabled }}
  CELERY_BROKER_URL: {{
      printf "amqp://%s:%s@%s:5672/celery"
          (required ".Values.rabbitmq.auth.username" .Values.rabbitmq.auth.username)
          (required ".Values.rabbitmq.auth.password" .Values.rabbitmq.auth.password)
          (include "common.names.fullname" .Subcharts.rabbitmq)
      }}
  HEALTHCHECK_RABBITMQ_URL: {{
      printf "amqp://%s:%s@%s:5672/celery"
          (required ".Values.rabbitmq.auth.username" .Values.rabbitmq.auth.username)
          (required ".Values.rabbitmq.auth.password" .Values.rabbitmq.auth.password)
          (include "common.names.fullname" .Subcharts.rabbitmq)
      }}
  {{- else }}
  CELERY_BROKER_URL: {{ required "secrets.CELERY_BROKER_URL" .Values.env.CELERY_BROKER_URL | quote }}
  HEALTHCHECK_RABBITMQ_URL: {{ required "secrets.HEALTHCHECK_RABBITMQ_URL" .Values.env.HEALTHCHECK_RABBITMQ_URL | quote }}
  {{- end }}

  # Redis
  {{- if .Values.redis.enabled }}
  CELERY_RESULT_BACKEND: "redis://{{ printf "%s-master" (include "common.names.fullname" .Subcharts.redis) }}:6379/0"
  HEALTHCHECK_REDIS_URL: "redis://{{ printf "%s-master" (include "common.names.fullname" .Subcharts.redis) }}:6379/1"
  {{- else }}
  CELERY_RESULT_BACKEND: {{ required "secrets.CELERY_RESULT_BACKEND" .Values.env.CELERY_RESULT_BACKEND | quote }}
  HEALTHCHECK_REDIS_URL: {{ required "secrets.HEALTHCHECK_REDIS_URL" .Values.env.HEALTHCHECK_REDIS_URL | quote }}
  {{- end }}

  {{- if .Values.minio.enabled }}
  # Minio
  AWS_S3_ENDPOINT_URL: "https://{{ .Values.minio.apiIngress.hostname }}/"
  AWS_S3_ACCESS_KEY_ID: {{ required ".Values.minio.auth.rootUser" .Values.minio.auth.rootUser }}
  AWS_S3_SECRET_ACCESS_KEY: {{ required ".Values.minio.auth.rootPassword" .Values.minio.auth.rootPassword }}
  AWS_S3_REGION: "us-east-1"
  {{- end }}

  # Geocoding
  {{- if .Values.geocoding.enabled }}
  GEOCODER_URL: {{ printf "http://%s:80" (include "goecoding-helm.servicename" .Subcharts.geocoding) | quote }}
  {{- else }}
  GEOCODER_URL: {{ required "secrets.GEOCODER_URL" .Values.secrets.GEOCODER_URL | quote }}
  {{- end}}

  # Geocoding lite
  {{- if .Values.geocodingLite.enabled }}
  GEOCODER_LITE_URL: {{ printf "http://%s:80" (include "goecoding-helm.servicename" .Subcharts.geocodingLite) | quote }}
  {{- else }}
  GEOCODER_LITE_URL: {{ required "secrets.GEOCODER_LITE_URL" .Values.secrets.GEOCODER_LITE_URL | quote }}
  {{- end}}

  # ETL Sources
  EMDAT_AUTHORIZATION_KEY: {{ required "secrets.EMDAT_AUTHORIZATION_KEY" .Values.secrets.EMDAT_AUTHORIZATION_KEY | quote }}
  GFD_CREDENTIAL: {{ required "secrets.GFD_CREDENTIAL" .Values.secrets.GFD_CREDENTIAL | quote }}
  GFD_SERVICE_ACCOUNT: {{ required "secrets.GFD_SERVICE_ACCOUNT" .Values.secrets.GFD_SERVICE_ACCOUNT | quote }}
  IDMC_CLIENT_ID: {{ required "secrets.IDMC_CLIENT_ID" .Values.secrets.IDMC_CLIENT_ID | quote }}
  PDC_ARCGIS_USERNAME: {{ required "secrets.PDC_ARCGIS_USERNAME" .Values.secrets.PDC_ARCGIS_USERNAME | quote }}
  PDC_ARCGIS_PASSWORD: {{ required "secrets.PDC_ARCGIS_PASSWORD" .Values.secrets.PDC_ARCGIS_PASSWORD | quote }}
  PDC_SENTRY_AUTHORIZATION_KEY: {{ required "secrets.PDC_SENTRY_AUTHORIZATION_KEY" .Values.secrets.PDC_SENTRY_AUTHORIZATION_KEY | quote }}

  # Additional secrets
  {{- range $name, $value := .Values.secretsAdditional }}
  {{ $name }}: {{ $value | quote }}
  {{- end }}

{{- end }}
