app:
  fullnameOverride: monty-etl

  podLabels:
    azure.workload.identity/use: 'true'

  ingress:
    enabled: true
    className: nginx
    tls:
      enabled: true

  env:
    DJANGO_DEBUG: "false"
    DJANGO_TIME_ZONE: UTC
    DJANGO_ALLOWED_HOSTS: "*"
    # Azure configs
    # AZURE_STORAGE_ENABLE: XXX: go-deploy
    # AZURE_STORAGE_ACCOUNT_NAME: XXX: go-deploy
    # AZURE_STORAGE_MEDIA_CONTAINER: XXX: go-deploy
    # AZURE_STORAGE_STATIC_CONTAINER: XXX: go-deploy
    # ETL Load config
    # EOAPI_DOMAIN: XXX: go-deploy

  serviceAccountName: "service-token-reader"
  serviceAccount:
    create: true
    automountServiceAccountToken: true
    # annotations:
    #   azure.workload.identity/client-id: # XXX: go-deploy
    labels:
      azure.workload.identity/use: "true"

  secretsStoreCsiDriver:
    create: true
    provider: azure
    parameters:
      usePodIdentity: "false"
      # clientID: # XXX: go-deploy
      # keyvaultName: # XXX: go-deploy
      # tenantId: # XXX: go-deploy
    secretsKeyMap:
      # DB
      DB_HOST: DB-HOST
      DB_NAME: DB-NAME
      DB_PASSWORD: DB-PASSWORD
      DB_PORT: DB-PORT
      DB_USER: DB-USER
      # Misc
      DJANGO_SECRET_KEY: DJANGO-SECRET-KEY
      SENTRY_DSN: SENTRY-DSN
      # ETL sources config
      EMDAT_AUTHORIZATION_KEY: EMDAT-AUTHORIZATION-KEY
      GFD_CREDENTIAL: GFD-CREDENTIAL
      GFD_SERVICE_ACCOUNT: GFD-SERVICE-ACCOUNT
      IDMC_CLIENT_ID: IDMC-CLIENT-ID
      PDC_ARCGIS_USERNAME: PDC-ARCGIS-USERNAME
      PDC_ARCGIS_PASSWORD: PDC-ARCGIS-PASSWORD
      PDC_SENTRY_AUTHORIZATION_KEY: PDC-SENTRY-AUTHORIZATION-KEY
