# Generated by Django 5.1.3 on 2024-11-21 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(choices=[(0, 'Africa'), (1, 'Americas'), (2, 'Asia Pacific'), (3, 'Europe'), (4, 'Middle East & North Africa')], verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='name')),
                ('iso3', models.CharField(blank=True, max_length=3, null=True, verbose_name='iso3')),
                ('iso', models.CharField(blank=True, max_length=2, null=True, verbose_name='iso2')),
                ('record_type', models.IntegerField(blank=True, choices=[(1, 'Country'), (2, 'Cluster'), (3, 'Region'), (4, 'Country Office'), (5, 'Representative Office')], help_text='Type of entity', null=True, verbose_name='type')),
                ('bbox', models.JSONField(blank=True, default=dict, null=True, verbose_name='bbox')),
                ('centroid', models.JSONField(blank=True, default=dict, null=True, verbose_name='centroid')),
                ('independent', models.BooleanField(default=None, help_text='Is this an independent country?', null=True)),
                ('is_deprecated', models.BooleanField(default=False, help_text='Is this an active, valid country?')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.region', verbose_name='region')),
            ],
        ),
    ]
