apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "montandon-etl.fullname" . }}-local-cache
  labels:
    app: {{ include "montandon-etl.fullname" . }}
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.localCacheVolume.storageClass }}
  resources:
    requests:
      storage: {{ .Values.localCacheVolume.size }}
