apiVersion: v2
name: montandon-etl-helm
description: "Helm Chart to deploy the IFRC GO Risk Module Infrastructure"
type: application
version: 0.0.1-SET-BY-CICD
sources:
  - https://github.com/IFRCGo/montandon-etl/

dependencies:
  - name: redis
    version: 20.6.3
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: postgresql
    version: 16.4.5
    condition: postgresql.enabled
    repository: https://charts.bitnami.com/bitnami
  - name: minio
    version: 14.10.5
    condition: minio.enabled
    repository: https://charts.bitnami.com/bitnami
  - name: geocoding-helm
    alias: geocoding
    version: 0.0.1-c9dd1963
    condition: geocoding.enabled
    repository: oci://ghcr.io/ifrcgo/geocoding-service
