apiVersion: v2
name: montandon-etl-helm
description: "Helm Chart to deploy the IFRC GO Montandon ETL Infrastructure"
type: application
version: 0.1.1-SET-BY-CICD  # managed by release.sh
sources:
  - https://github.com/IFRCGo/montandon-etl/

dependencies:
  - name: banjo-helm
    alias: app
    version: 0.2.8
    repository: oci://ghcr.io/toggle-corp
  - name: geocoding-helm
    alias: geocoding
    version: 0.0.1-main.632a89a
    condition: geocoding.enabled
    repository: oci://ghcr.io/ifrcgo/geocoding-service
