# https://github.com/IFRCGo/geocoding-service/blob/main/helm/values.yaml
geocoding:
  enabled: true
  fullnameOverride: geocoder
  image:
    # TODO: Why?
    tag: main.c26a216
  server:
    serviceName: monty-geocoder  # NOTE: This is used in app using extraEnvVars
    resources:
      requests:
        cpu: "0.1"
        memory: 1.5Gi
      limits:
        cpu: "4"
        memory: 3Gi
    persistence:
      enabled: true
      storageClassName: default
      size: 3Gi

app:
  environment: PROD
  nameOverride: ifrcgo-monty-etl-helm

  appTypeEnvName: "DJANGO_APP_TYPE"

  # Global Image
  image:
    name: SET-BY-CICD-IMAGE
    tag: SET-BY-CICD-TAG
    imagePullPolicy: IfNotPresent

  ingress:
    enabled: true
    className:
    host:

  minio:
    enabled: false
    disableWebUI: true
    mode: standalone
    fullnameOverride: montandon-etl-minio
    global:
      defaultStorageClass:
    apiIngress:
      enabled: true
      ingressClassName:  # NOTE: Define me when used
      hostname:  # NOTE: Define me when used
      annotations:
        nginx.ingress.kubernetes.io/proxy-body-size: "500m"
    auth:
      forceNewKeys: True
      rootUser: monty-etl
      rootPassword:  # NOTE: Define me when used
    resources:
      requests:
        cpu: "0.1"
        memory: 128Mi
      limits:
        cpu: "4"
        memory: 256Mi
    persistence:
      enabled: true
      size: 1Gi
    defaultBuckets: montandon-etl-data,montandon-etl-static  # XXX: Don't change this
    provisioning:
      enabled: true
      resourcesPreset: "nano"
      cleanupAfterFinished:
        enabled: true
      extraCommands:
        - "mc anonymous set download provisioning/montandon-etl-static"
        - "mc anonymous set download provisioning/montandon-etl-data"

  redis:
    enabled: false
    fullnameOverride: montandon-etl-redis
  rabbitmq:
    enabled: false
    fullnameOverride: montandon-etl-rabbitmq

  api:
    enabled: true
    replicaCount: 1
    containerPort: 80
    command: ["/code/scripts/run_web.sh"]
    resources:
      requests:
        cpu: "0.1"
        memory: 1Gi
      limits:
        cpu: "4"
        memory: 2Gi

  worker:
    enabled: true
    beat:
      command: ["celery", "-A", "main", "beat", "-l", "INFO"]
      resources:
        requests:
          cpu: "0.1"
          memory: 0.2Gi
        limits:
          cpu: "1"
          memory: 0.5Gi
    flower:
      enabled: true
      command: ["celery", "-A", "main", "flower", "--port=8000"]
      resources:
        requests:
          cpu: "0.1"
          memory: 0.5Gi
        limits:
          cpu: "1"
          memory: 0.5Gi
    queueDefaultResources:
      requests:
        cpu: "0.1"
        memory: 1Gi
      limits:
        cpu: "4"
        memory: 2Gi
    queueCommandPrefix:
      - "celery"
      - "-A"
      - "main"
      - "worker"
      - "-l"
      - "INFO"
      - "--prefetch-multiplier"
      - "1"
    queues:
      # NOTE: Make sure keys are lowercase
      default:
        enabled: true
        replicaCount: 1
        celeryArgs: ["-Q", "default", "--concurrency", "5", "--max-tasks-per-child", "25"]
      extraction:
        enabled: true
        replicaCount: 1
        celeryArgs: ["-Q", "extraction", "--concurrency", "2", "--max-tasks-per-child", "25"]
      transform:
        enabled: true
        replicaCount: 2
        celeryArgs: ["-Q", "transform", "--concurrency", "2", "--max-tasks-per-child", "25"]
      # By source
      # TODO: Is this used?
      usgs-extraction:
        enabled: true
        replicaCount: 1
        celeryArgs: ["-Q", "usgs-extraction", "--concurrency", "2", "--max-tasks-per-child", "25"]

  argoHook:
    enabled: true
    resources:
      requests:
        cpu: "0.1"
        memory: 1Gi
      limits:
        cpu: "4"
        memory: 2Gi
    hooks:
      # NOTE: Make sure keys are lowercase
      db-migrate:
        enabled: true
        hook: PostSync
        preserveHistory: true
        command: ["./manage.py", "migrate"]
      collect-static:
        enabled: true
        hook: PostSync
        command: ["./manage.py", "collectstatic", "--noinput"]

  env:
    APP_RELEASE: "{{ $.Values.image.tag }}"
    DJANGO_APP_ENVIRONMENT: "{{ $.Values.environment }}"
    DJANGO_DEBUG: "false"
    DJANGO_TIME_ZONE: UTC
    # App Domain
    DJANGO_ALLOWED_HOSTS: "*"
    # Azure configs
    AZURE_STORAGE_ENABLE: "false"
    # ETL app config
    EOAPI_STAC_API: "{{ required \".app.secrets.EOAPI_STAC_API\" nil }}"

  secrets:
    DJANGO_SECRET_KEY: "{{ required \".app.secrets.DJANGO_SECRET_KEY\" nil }}"
    # Sentry
    SENTRY_DSN: "{{ required \".app.secrets.SENTRY_DSN\" nil }}"
    # ETL sources config
    EMDAT_AUTHORIZATION_KEY: "{{ required \".app.secrets.EMDAT_AUTHORIZATION_KEY\" nil }}"
    GFD_CREDENTIAL: "{{ required \".app.secrets.GFD_CREDENTIAL\" nil }}"
    GFD_SERVICE_ACCOUNT: "{{ required \".app.secrets.GFD_SERVICE_ACCOUNT\" nil }}"
    IDMC_CLIENT_ID: "{{ required \".app.secrets.IDMC_CLIENT_ID\" nil }}"
    PDC_ARCGIS_USERNAME: "{{ required \".app.secrets.PDC_ARCGIS_USERNAME\" nil }}"
    PDC_ARCGIS_PASSWORD: "{{ required \".app.secrets.PDC_ARCGIS_PASSWORD\" nil }}"
    PDC_SENTRY_AUTHORIZATION_KEY: "{{ required \".app.secrets.PDC_SENTRY_AUTHORIZATION_KEY\" nil }}"

  extraEnvVars:
    # -- Geocoder
    - name: GEOCODER_URL
      value: http://monty-geocoder:80
